# Site settings
title: Portfolio
email: egarcia9889@gmail.com
url: http://127.0.0.1:4000/
description: "My Portfolio Website"
baseurl: 

# Footer settings
footer: Designed and developed by Eva Garcia | Copyright 2017 

# Social networks usernames 
social:
  - title: Instagram
    url: https://www.instagram.com/design_evamariagarcia/
  - title: Github
    url: https://github.com/EvaMariaGarcia
  - title: Tumblr
    url: https://evamariagarcia-blog.tumblr.com

# Build settings
markdown: kramdown
permalink: pretty